ticket_admin/bank/urls.py
from django.urls import path

from ticket_admin.bank import views

app_name = 'bank'

urlpatterns = [
    path('', views.BankListView.as_view(), name='list'),
    path('formulario/', views.BankCreateView.as_view(), name='create'),
    path('formulario/<uuid:uuid>/', views.BankUpdateView.as_view(), name='update'),
    path('<uuid:uuid>/', views.BankDeleteView.as_view(), name='delete'),
]

ticket_admin/core/urls.py
from django.urls import path

from ticket_admin.core import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('configuracao/', views.ConfigView.as_view(), name='config'),
    path('redefinir-senha/', views.PasswordResetView.as_view(), name='password-reset'),

    # TUTORIAL
    path('tutorial/', views.TutorialView.as_view(), name='list-tutorial'),
    path('tutorial/<uuid:uuid>', views.TutorialDetailView.as_view(), name='detail-tutorial'),
]

ticket_admin/custom_profile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from ticket_admin.custom_profile import views, forms

app_name = 'profile'

urlpatterns = [
    path('entrar/', auth_views.LoginView.as_view(authentication_form=forms.LoginForm), name='login'),
    path('sair/', auth_views.LogoutView.as_view(), name='logout'),

    path('', views.ProfileListView.as_view(), name='list'),
    path('formulario/', views.ProfileCreateView.as_view(), name='create'),
    path('formulario/<uuid:uuid>/', views.ProfileUpdateView.as_view(), name='update'),
    path('<uuid:uuid>/', views.ProfileDeleteView.as_view(), name='delete'),

    path('usuario/', views.ProfileUserListView.as_view(), name='user-list'),
    path('usuario/formulario/', views.ProfileUserCreateView.as_view(), name='user-create'),
    path('usuario/formulario/<uuid:uuid>/', views.ProfileUserUpdateView.as_view(),
         name='user-update'),
    path('usuario/<uuid:uuid>/', views.ProfileUserDeleteView.as_view(), name='user-delete'),
]

ticket_admin/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

# Admin customization.
admin.site.site_header = 'Painel IPTV'
admin.site.site_title = 'Painel IPTV'
admin.site.index_title = 'Administração'


urlpatterns = [
    path('admin/', admin.site.urls),

    # API
    path('api/v1/', include('ticket_admin.api.v1.urls', namespace='api-v1')),

    # HOME
    path('', include('ticket_admin.core.urls', namespace='core')),

    # PROFILE
    path('cliente/', include('ticket_admin.custom_profile.urls', namespace='profile')),

    # BILLET
    path('boleto/', include('ticket_admin.billet.urls', namespace='billet')),

    # PANEL
    path('painel/', include('ticket_admin.panel.urls', namespace='panel')),

    # BANK
    path('banco/', include('ticket_admin.bank.urls', namespace='bank')),

    # PAYMENT
    path('pagamento/', include('ticket_admin.payment.urls', namespace='payment')),
]

if settings.DEFAULT_FILE_STORAGE == 'django.core.files.storage.FileSystemStorage':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket_admin/core/models.py
from uuid import uuid4

from auditlog.registry import auditlog
from auditlog.models import AuditlogHistoryField

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from ticket_admin.core.manager import Manager
from ticket_admin.storage import get_storage_path
from ticket_admin.core.signals import post_soft_delete


def get_tutorial_file_path(instance, filename):
    return get_storage_path(filename, 'tutorial')


class AbstractBaseModel(models.Model):

    class Meta:
        abstract = True

    history = AuditlogHistoryField()
    uuid = models.UUIDField(verbose_name='UUID', default=uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(verbose_name=_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name=_('Updated at'), auto_now=True)
    deleted_at = models.DateTimeField(verbose_name=_('Deleted at'), null=True, blank=True)
    objects = Manager()
    objects_all = models.Manager()

    def delete(self):
        self.deleted_at = timezone.now()
        self.save()
        post_soft_delete.send(sender=type(self), instance=self, using=self._state.db)

    def __str__(self):
        if hasattr(self, 'name'):
            return self.name
        if hasattr(self, 'title'):
            return self.title
        return str(self.pk)


class Config(AbstractBaseModel):

    class Meta:
        verbose_name = 'Configuração'
        verbose_name_plural = 'Configurações'

    user = models.OneToOneField(User, verbose_name='Usuário', on_delete=models.CASCADE, related_name='config')
    token = models.CharField(verbose_name='Token', max_length=255)
    instructions_billet = models.CharField(verbose_name='Instruções', max_length=100)
    description_billet = models.CharField(verbose_name='Descrição', max_length=100)


class Tutorial(AbstractBaseModel):

    class Meta:
        verbose_name = 'Tutorial'
        verbose_name_plural = 'Tutoriais'
        ordering = ['order', 'name']
        permissions = [
            ('list_tutorial', 'Pode Listar Tutoriais'),
        ]

    name = models.CharField(verbose_name='Nome', max_length=255)
    url = models.URLField(verbose_name='Url', null=True, blank=True)
    order = models.PositiveSmallIntegerField(verbose_name='Ordem', default=0)


class TutorialImage(AbstractBaseModel):

    class Meta:
        verbose_name = 'Imagem'
        verbose_name_plural = 'Imagens'

    tutorial = models.ForeignKey(Tutorial, verbose_name='Tutorial', on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(verbose_name='Imagem', upload_to=get_tutorial_file_path)
    title = models.CharField(verbose_name='Título', max_length=255, null=True, blank=True)
    description = models.TextField(verbose_name='Descrição', null=True, blank=True)


auditlog.register(User)
auditlog.register(Config)
auditlog.register(Tutorial)
auditlog.register(TutorialImage)

ticket_admin/core/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password

from ticket_admin.core import models


class ConfigForm(forms.ModelForm):

    class Meta:
        model = models.Config
        exclude = ['deleted_at']

    email = forms.EmailField(label='Email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and hasattr(self.instance, 'user'):
            self.fields.get('email').initial = self.instance.user.email


class PasswordResetForm(forms.Form):

    password_old = forms.CharField(label='Senha antiga', widget=forms.PasswordInput())
    password = forms.CharField(label='Nova senha', widget=forms.PasswordInput())
    password1 = forms.CharField(label='Confirme sua nova senha', widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def clean_password_old(self):
        value = self.cleaned_data.get('password_old')
        if not self.user.check_password(value):
            raise forms.ValidationError('Senha inválida!')
        return value

    def clean_password(self):
        value = self.cleaned_data.get('password')
        validate_password(value)
        return value

    def clean(self):
        password = self.cleaned_data.get('password')
        password1 = self.cleaned_data.get('password1')
        if (password and password1) and (password != password1):
            self.add_error('password1', 'Senhas não são iguais!')

        return self.cleaned_data

    def save(self):
        self.user.set_password(self.cleaned_data.get('password'))
        self.user.save()

ticket_admin/core/views.py
from datetime import datetime, timedelta

from django.views import View
from django.db.models import Q
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from ticket_admin.core import models, forms
from ticket_admin.billet.models import Billet
from ticket_admin.custom_profile.models import Profile, ProfileUser


class BaseView(PermissionRequiredMixin, SuccessMessageMixin, View):

    raise_exception = True
    permission_required = []

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if request.user.has_perm('billet.list_billet'):
            url_allowed = [
                reverse_lazy('core:config'),
            ]
            if not request.get_full_path() in url_allowed and not hasattr(request.user, 'config'):
                messages.warning(request, 'Configure sua conta antes de continuar!')
                return redirect(reverse_lazy('core:config'))
        return super().dispatch(request, *args, **kwargs)


class BaseListView(BaseView, ListView):

    paginate_by = 50

    def get_queryset(self):
        paginate_by = self.request.GET.get('paginate_by')
        if paginate_by:
            self.paginate_by = paginate_by
        return super().get_queryset()


class BaseCreateView(BaseView, CreateView):

    pass


class BaseUpdateView(BaseView, UpdateView):

    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'


class BaseDeleteView(BaseView, DeleteView):

    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(BaseDeleteView, self).delete(request, *args, **kwargs)


class BaseDetailView(BaseView, DetailView):

    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'


class HomeView(BaseView):

    template_name = 'core/home.html'

    def get_context_data(self):
        user = self.request.user
        query_user = ProfileUser.objects.filter(profile__user=user)

        billing = ProfileUser.objects.get_billing(user)
        credit_cost = ProfileUser.objects.get_credit_costs(user)

        context = {
            'clients': Profile.objects.filter(user=user).count(),
            'users': ProfileUser.objects.filter(profile__user=user).count(),
            'users_active': query_user.filter(status=ProfileUser.ACTIVE).count(),
            'users_waiting': query_user.filter(status=ProfileUser.WAITING).count(),
            'users_expired': query_user.filter(status=ProfileUser.EXPIRED).count(),
            'billing': billing,
            'credit_cost': credit_cost,
            'billing_liquid': billing - credit_cost
        }
        if user.has_perm('billet.list_billet'):
            context['billets_wainting'] = Billet.objects.filter(
                profile__user=user, status=Billet.WAITING).count()
            context['billets_debited'] = Billet.objects.filter(
                Q(status=Billet.PAID) | Q(status=Billet.DEBITED),
                profile__user=user).count()
            context['billets_canceled'] = Billet.objects.filter(
                profile__user=user, status=Billet.CANCELED).count()
            context['billing_billet'] = Billet.objects.get_billing(user)
        return context

    def get(self, request):
        query_user = ProfileUser.objects.filter(profile__user=self.request.user)
        now = datetime.now().date()
        ten = now + timedelta(days=10)
        for user in query_user:
            if user.expiration < now:
                status = ProfileUser.EXPIRED
            elif user.expiration <= ten:
                status = ProfileUser.WAITING
            else:
                status = ProfileUser.ACTIVE
            user.status = status
            user.save()
        return render(request, self.template_name, self.get_context_data())


class ConfigView(BaseView):

    model = models.Config
    form_class = forms.ConfigForm
    template_name = 'core/config.html'
    success_message = 'Configuração salva!'
    success_url = reverse_lazy('core:config')

    def get_object(self):
        return self.model.objects.filter(user=self.request.user).first()

    def get_context_data(self):
        context = {'form': self.form_class(instance=self.get_object())}
        return context

    def get(self, request):
        return render(request, self.template_name, self.get_context_data())

    def post(self, request):
        context = self.get_context_data()
        data = request.POST.copy()
        data['user'] = request.user.pk
        form = self.form_class(instance=self.get_object(), data=data)

        if form.is_valid():
            form.save()
            request.user.email = form.cleaned_data.get('email')
            request.user.save()
            messages.success(request, self.success_message)
            return redirect(self.success_url)
        context['form'] = form
        return render(request, self.template_name, context=context)


class PasswordResetView(BaseView):

    form_class = forms.PasswordResetForm
    template_name = 'core/password-reset.html'
    success_message = 'Senha redefinida! Faça o login com sua nova senha.'
    success_url = reverse_lazy('core:home')

    def get_context_data(self):
        context = {'form': self.form_class(user=self.request.user)}
        return context

    def get(self, request):
        return render(request, self.template_name, self.get_context_data())

    def post(self, request):
        context = self.get_context_data()
        form = self.form_class(data=request.POST, user=self.request.user)

        if form.is_valid():
            form.save()
            messages.success(request, self.success_message)
            return redirect(self.success_url)
        context['form'] = form
        return render(request, self.template_name, context=context)


class TutorialView(BaseListView):

    model = models.Tutorial
    template_name = 'core/tutorial/list.html'
    permission_required = ['core.list_tutorial']


class TutorialDetailView(BaseDetailView):

    model = models.Tutorial
    template_name = 'core/tutorial/detail.html'
    permission_required = ['core.view_tutorial']

ticket_admin/core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <title>Gringo TV</title>

  <link rel="shortcut icon" type="image/png" href="{% static 'img/logo.png' %}" />

  <!-- FONT GOOGLE -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'plugins/adminlte/css/_all-skins.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/adminlte/css/AdminLTE.min.css' %}">

  {% if DEBUG %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
  {% else %}
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.min.css' %}">
  {% endif %}
  {% block css %}{% endblock %}
</head>
<body class="hold-transition skin-black sidebar-mini">
  <div class="wrapper">
    {% include 'header.html' %}

    <div class="content-wrapper position-relative px-3 pb-3 pt-0">{% block content %}{% endblock %}</div>

    {% include 'core/components/message.html' %}

    {% block modal %}{% endblock %}

    <div class="control-sidebar-bg"></div>
  
    {% include 'footer.html' %}
  </div>

  <!-- JQUERY -->
  <script src="{% static 'plugins/jquery/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'plugins/jquery/jquery.mask.min.js' %}"></script>
  <!-- BOOTSTRAP -->
  <script src="{% static 'plugins/bootstrap/js/popper.min.js' %}"></script>
  <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'plugins/adminlte/js/adminlte.min.js' %}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{% static 'plugins/adminlte/js/demo.js' %}"></script>

  {% if DEBUG %}
    <script src="{% static 'js/main.js' %}"></script>
  {% else %}
    <script src="{% static 'js/main.min.js' %}"></script>
  {% endif %}
  {% block js %}{% endblock %}
</body>
</html>

ticket_admin/core/templates/footer.html
<footer class="main-footer">
  <div class="float-right hidden-xs">
    <small class="font-weight-extraLight">
      Desenvolvido por 
      <a href="https://cosmunsoftwares.com.br/" target="_blank">
        Cosmun Softwares
      </a>
    </small>
  </div>
  <strong>Copyright &copy; 2020</strong>
</footer>

ticket_admin/core/templates/header.html
<header class="main-header">
  <a href="{% url 'core:home' %}" class="logo font-weight-bold border-0 text-white  d-flex justify-content-center align-items-center">
    <span class="logo-mini">GTV</span>
    <span class="logo-lg">Gringo TV</span>
  </a>
  <nav class="navbar navbar-static-top pl-2">
    <a href="#" class="sidebar-toggle border-0 px-4" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'profile:logout' %}" class="py-3 px-4" title="Sair">
            <i class="fas fa-power-off"></i>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</header>

<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
      <div class="info">
        <p>Bem-vindo</p>
        <p>{{ user }}</p>
      </div>
    </div>
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header text-uppercase text-white">Menu</li>
      <li><a href="{% url 'core:home' %}"><i class="fas fa-home mr-2"></i><span>Início</span></a></li>
      {% if perms.custom_profile.list_profile or perms.custom_profile.list_profileuser or perms.billet.list_billet %}
        <li class="treeview">
          <a href="#">
            <i class="fas fa-users mr-2"></i><span>Clientes</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            {% if perms.custom_profile.list_profile %}
              <li><a href="{% url 'profile:list' %}"><i class="fas fa-users mr-2"></i><span>Clientes</span></a></li>
            {% endif %}
            {% if perms.custom_profile.list_profileuser %}
              <li><a href="{% url 'profile:user-list' %}"><i class="fas fa-user mr-2"></i><span>Usuários</span></a></li>
            {% endif %}
            {% if perms.billet.list_billet %}
              <li><a href="{% url 'billet:list' %}"><i class="fas fa-barcode mr-2"></i><span>Boletos</span></a></li>
            {% endif %}
          </ul>
        </li>
      {% endif %}
      {% if perms.panel.list_panel %}
        <li><a href="{% url 'panel:list' %}"><i class="fas fa-tv mr-2"></i><span>Painéis</span></a></li>
      {% endif %}
      {% if perms.bank.list_bank %}
        <li><a href="{% url 'bank:list' %}"><i class="fas fa-university mr-2"></i><span>Bancos</span></a></li>
      {% endif %}
      {% if perms.core.list_tutorial %}
        <li><a href="{% url 'core:list-tutorial' %}"><i class="fas fa-graduation-cap mr-2"></i><span>Tutoriais</span></a></li>
      {% endif %}
      {% if perms.payment.list_payment %}
        <li><a href="{% url 'payment:list' %}"><i class="fas fa-dollar-sign mr-2"></i><span>Pagamentos</span></a></li>
      {% endif %}
      <li class="treeview">
        <a href="#">
          <i class="fas fa-cogs mr-2"></i><span>Configurações</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          {% if perms.billet.list_billet %}
            <li><a href="{% url 'core:config' %}"><i class="fas fa-barcode mr-2"></i><span>Boleto</span></a></li>
          {% endif %}
          <li><a href="{% url 'core:password-reset' %}"><i class="fas fa-key mr-2"></i><span>Redefinir senha</span></a></li>
        </ul>
      </li>
    </ul>
  </section>
</aside>