ticket_admin/payment/urls.py
from django.urls import path

from ticket_admin.payment import views

app_name = 'payment'

urlpatterns = [
    path('', views.PaymentListView.as_view(), name='list'),
    path('formulario/', views.PaymentCreateView.as_view(), name='create'),
    path('detalhe/<uuid:uuid>/', views.PaymentDetailView.as_view(), name='detail'),
    path('<uuid:uuid>/', views.PaymentDeleteView.as_view(), name='delete'),
]

ticket_admin/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

# Admin customization.
admin.site.site_header = 'Painel IPTV'
admin.site.site_title = 'Painel IPTV'
admin.site.index_title = 'Administração'


urlpatterns = [
    path('admin/', admin.site.urls),

    # API
    path('api/v1/', include('ticket_admin.api.v1.urls', namespace='api-v1')),

    # HOME
    path('', include('ticket_admin.core.urls', namespace='core')),

    # PROFILE
    path('cliente/', include('ticket_admin.custom_profile.urls', namespace='profile')),

    # BILLET
    path('boleto/', include('ticket_admin.billet.urls', namespace='billet')),

    # PANEL
    path('painel/', include('ticket_admin.panel.urls', namespace='panel')),

    # BANK
    path('banco/', include('ticket_admin.bank.urls', namespace='bank')),

    # PAYMENT
    path('pagamento/', include('ticket_admin.payment.urls', namespace='payment')),
]

if settings.DEFAULT_FILE_STORAGE == 'django.core.files.storage.FileSystemStorage':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket_admin/payment/models.py
from auditlog.registry import auditlog

from django.db import models
from django.contrib.auth.models import User

from ticket_admin.storage import get_storage_path
from ticket_admin.core.models import AbstractBaseModel


def get_file_path(instance, filename):
    return get_storage_path(filename, 'payment')


class Payment(AbstractBaseModel):

    class Meta:
        verbose_name = 'Pagamento'
        verbose_name_plural = 'Pagamentos'
        ordering = ['-created_at']
        permissions = [
            ('list_payment', 'Pode Listar Pagamentos'),
        ]

    IN_ANALYZE = 'in_analyze'
    APPROVED = 'approved'
    NOT_APPROVED = 'not_approved'

    STATUS = [
        (APPROVED, 'Aprovado'),
        (IN_ANALYZE, 'Em análise'),
        (NOT_APPROVED, 'Não aprovado')
    ]

    user = models.ForeignKey(User, verbose_name='Usuário', on_delete=models.CASCADE, related_name='payments')
    image = models.ImageField(verbose_name='Imagem', upload_to=get_file_path)
    date = models.DateField(verbose_name='Data')
    status = models.CharField(verbose_name='Status', max_length=255, choices=STATUS, default=IN_ANALYZE)
    message = models.TextField(verbose_name='Mensagem', null=True, blank=True)


auditlog.register(Payment)

ticket_admin/payment/forms.py
from django import forms

from ticket_admin.payment import models


class PaymentForm(forms.ModelForm):

    class Meta:
        model = models.Payment
        exclude = ['user', 'status', 'deleted_at']
        widgets = {
            'date': forms.HiddenInput()
        }

    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'd-none'}), required=False)

ticket_admin/api/v1/payment/views.py
from rest_framework import status
from rest_framework import viewsets
from rest_framework.response import Response

from django.shortcuts import get_object_or_404

from ticket_admin.billet.models import Billet
from ticket_admin.billet.pagseguro import Pagseguro


class PaymentViewSet(viewsets.ViewSet):

    pagseguro = Pagseguro()
    model = Billet

    def get_object(self, code):
        return get_object_or_404(self.model, code=code)

    def post(self, request):
        code = request.data.get('notificationCode')
        response = self.pagseguro.get_notification(code)
        if response.ok:
            result = response.json()
            obj = self.get_object(result.get('code'))
            obj.status = result.status
            obj.save()

            return Response({'ok': 'Atualizado!'}, status=status.HTTP_200_OK)
        return Response({'error': response.text}, status=status.HTTP_400_BAD_REQUEST)

ticket_admin/payment/views.py
from datetime import datetime

from django.urls import reverse_lazy

from ticket_admin.core import views
from ticket_admin.payment import models, forms


class PaymentListView(views.BaseListView):

    model = models.Payment
    template_name = 'payment/list.html'
    permission_required = ['payment.list_payment']

    def get_queryset(self):
        object_list = super().get_queryset().filter(user=self.request.user)
        text_filter = self.request.GET.get('q')
        if text_filter:
            object_list = object_list.filter(name__icontains=text_filter)
        return object_list


class PaymentCreateView(views.BaseCreateView):

    model = models.Payment
    form_class = forms.PaymentForm
    template_name = 'payment/form.html'
    success_url = reverse_lazy('payment:list')
    success_message = 'Pagamento cadastrado!'
    permission_required = ['payment.add_payment']
    initial = {
        'date': datetime.now().date()
    }

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PaymentDetailView(views.BaseDetailView):

    model = models.Payment
    template_name = 'payment/detail.html'
    permission_required = ['payment.view_payment']


class PaymentDeleteView(views.BaseDeleteView):

    model = models.Payment
    template_name = 'payment/list.html'
    success_url = reverse_lazy('payment:list')
    success_message = 'Painel deletado!'
    permission_required = ['payment.delete_payment']

ticket_admin/payment/templates/payment/detail.html
{% extends "base.html" %}
{% load staticfiles template_tags %}

{% block content %}

  <section class="content">
    <div class="box box-primary border-0 rounded-0 shadow-1">
      <div class="box-header">
        <i class="fas fa-eye mr-2"></i>
        <h3 class="box-title">Pagamento</h3>
      </div>
      <div class="box-body p-0">
        <table class="table table-striped">
          <tbody>
            <tr><th>Data:</th><td>{{ object.date }}</td></tr>
            <tr><th>Status:</th><td class="font-weight-bold text-{{ object.status|get_payment_color_status }}">{{ object.get_status_display }}</td></tr>
            {% if object.message %}
              <tr>
                <th>Mensagem:</th>
                <td>{{ object.message }}</td>
              </tr>
            {% endif %}
            <tr><th>Comprovante:</th><td><img src="{{ object.image.url }}" class="img-fluid col-4" alt=""></td></tr>
          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock %}
{% block modal %}
  {% url 'task:delete' object.uuid as url_delete %}

  {% include 'core/components/modal_confirm.html' with uuid=object.uuid url=url_delete %}
{% endblock %}

ticket_admin/payment/templates/payment/form.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <section class="content">
    <form method="POST" class="row position-relative" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="col-md-8">
        <div class="box box-primary border-0 rounded-0 shadow-1">
          <div class="box-header">
            <i class="fas fa-edit mr-2"></i>
            <h3 class="box-title">Formulário</h3>
          </div>
          <div class="box-body">
            {{ form.image }}
            <label for="{{ form.image.id_for_label }}" class="dropzone d-block p-5 text-center mb-0" style="cursor: pointer;">
              <span>Clique aqui para carregar o comprovante de pagamento!</span>
            </label>
            {% include 'core/components/field-error.html' with field=form.photo %}
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="box box-primary border-0 rounded-0 shadow-1">
          <div class="box-header">
            <i class="fas fa-calendar mr-2"></i>
            <h3 class="box-title">Data do pagamento</h3>
          </div>
          <div class="box-body">
            {{ form.date }}
            <div id="datetimepicker"></div>
          </div>
        </div>
      </div>
      <button type="submit" class="btn btn-primary flat-right rounded-circle"><i class="fas fa-save"></i></button>
    </form>
  </section>

{% endblock %}
{% block modal %}
  {% include 'core/components/form-error.html' with form=form %}
{% endblock %}
{% block css %}
  <link href="{% static 'plugins/datetimepicker/css/datetimepicker.min.css' %}" rel="stylesheet">
{% endblock %}
{% block js %}
  <script src="{% static 'plugins/moment/moment-with-locales.min.js' %}"></script>
  <script src="{% static 'plugins/locale/pt-br.js' %}"></script>
  <script src="{% static 'plugins/datetimepicker/js/datetimepicker.js' %}"></script>
  <script type="text/javascript">
    $(function(){
      // DATETIMEPICKER
      $('#datetimepicker').datetimepicker({
        inline: true,
        sideBySide: true,
        locale: 'pt-br',
        format: 'DD/MM/YYYY'
      });

      $("#datetimepicker").on("dp.change", function (e) {
        $('[name="date"]').val(e.date.format('YYYY-MM-DD'))
      });

      // UPLOAD IMAGE
      $('#id_image').change(function() {
        var $label = $(this).parent().find('label');
        var $span = $label.find('span');

        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function(e) {
            if(!$span.hasClass('d-none')){
              $span.addClass('d-none');
            }
            $label.append('<img src="'+e.target.result+'" class="img-fluid"/>');
          }
          reader.readAsDataURL(this.files[0]);
        }
      });
    })
  </script>
{% endblock %}

ticket_admin/payment/templates/payment/list.html
{% extends "base.html" %}
{% load template_tags %}

{% block content %}
  <section class="content">
    <div class="box box-primary border-0 rounded-0 shadow-1">
      <div class="box-header">
        <div class="row align-items-center">
          <div class="col-md-8">
            <i class="fas fa-list mr-2"></i>
            <h3 class="box-title">Pagamentos</h3>
          </div>
          <div class="col-md-4">
            <form class="pb-0" style="min-height: auto;">
              <div class="input-group mb-2">
                <input type="text" name="q" placeholder="Filtro" value="{{ request.GET.q }}" class="form-control">
                <div class="input-group-append">
                  <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="box-body text-center px-0">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th class="border-0 text-left pl-4">Data</th>
                <th class="border-0">Status</th>
                <th class="border-0" width="250">Ações</th>
              </tr>
            </thead>
            <tbody>
              {% for object in object_list %}
                <tr>
                  <td class="align-middle text-left pl-4">{{ object.date }}</td>
                  <td class="align-middle font-weight-bold text-{{ object.status|get_payment_color_status }}">{{ object.get_status_display }}</td>
                  <td>
                    <a href="{% url 'payment:detail' object.uuid %}" class="btn btn-outline-info" title="Detalhe"><i class="fas fa-eye"></i></a>
                    <button type="button" data-toggle="modal" data-target="#confirm-{{ object.uuid }}" class="btn btn-outline-danger" title="Deletar"><i class="fas fa-trash"></i></button>
                  </td>
                </tr>
              {% empty %}
                <tr><td colspan="6" class="text-center">Nenhum registro encontrado!</td></tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {% if is_paginated %}
          <div class="px-4">
            {% include 'core/components/pagination.html' with obj=page_obj paginator=paginator %}
          </div>
        {% endif %}
      </div>
    </div>
  </section>
  <a href="{% url 'payment:create' %}" class="btn btn-primary flat-right rounded-circle"><i class="fas fa-plus"></i></a>
{% endblock %}
{% block modal %}
  {% for object in object_list %}
    {% url 'payment:delete' object.uuid as url_delete %}

    {% include 'core/components/modal_confirm.html' with uuid=object.uuid url=url_delete %}
  {% endfor %}
{% endblock %}