ticket_admin/custom_profile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from ticket_admin.custom_profile import views, forms

app_name = 'profile'

urlpatterns = [
    path('entrar/', auth_views.LoginView.as_view(authentication_form=forms.LoginForm), name='login'),
    path('sair/', auth_views.LogoutView.as_view(), name='logout'),

    path('', views.ProfileListView.as_view(), name='list'),
    path('formulario/', views.ProfileCreateView.as_view(), name='create'),
    path('formulario/<uuid:uuid>/', views.ProfileUpdateView.as_view(), name='update'),
    path('<uuid:uuid>/', views.ProfileDeleteView.as_view(), name='delete'),

    path('usuario/', views.ProfileUserListView.as_view(), name='user-list'),
    path('usuario/formulario/', views.ProfileUserCreateView.as_view(), name='user-create'),
    path('usuario/formulario/<uuid:uuid>/', views.ProfileUserUpdateView.as_view(),
         name='user-update'),
    path('usuario/<uuid:uuid>/', views.ProfileUserDeleteView.as_view(), name='user-delete'),
]

ticket_admin/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

# Admin customization.
admin.site.site_header = 'Painel IPTV'
admin.site.site_title = 'Painel IPTV'
admin.site.index_title = 'Administração'


urlpatterns = [
    path('admin/', admin.site.urls),

    # API
    path('api/v1/', include('ticket_admin.api.v1.urls', namespace='api-v1')),

    # HOME
    path('', include('ticket_admin.core.urls', namespace='core')),

    # PROFILE
    path('cliente/', include('ticket_admin.custom_profile.urls', namespace='profile')),

    # BILLET
    path('boleto/', include('ticket_admin.billet.urls', namespace='billet')),

    # PANEL
    path('painel/', include('ticket_admin.panel.urls', namespace='panel')),

    # BANK
    path('banco/', include('ticket_admin.bank.urls', namespace='bank')),

    # PAYMENT
    path('pagamento/', include('ticket_admin.payment.urls', namespace='payment')),
]

if settings.DEFAULT_FILE_STORAGE == 'django.core.files.storage.FileSystemStorage':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket_admin/custom_profile/models.py
from auditlog.registry import auditlog

from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User

from ticket_admin.core.utils import Phone
from ticket_admin.panel.models import Panel
from ticket_admin.core.models import AbstractBaseModel
from ticket_admin.custom_profile.manager import ProfileUserManager


class Profile(AbstractBaseModel):

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfils'
        ordering = ['name', '-created_at']
        permissions = [
            ('list_profile', 'Pode Listar Perfils'),
        ]

    MONEY = 'active'
    BILLET = 'billet'
    TRANSFER = 'transfer'
    CREDIT_CARD = 'credit_card'

    PAY_METHOD = [
        (BILLET, 'Boleto'),
        (MONEY, 'Dinheiro'),
        (CREDIT_CARD, 'Cartão de Crédito'),
        (TRANSFER, 'Transferência bancária'),
    ]

    user = models.ForeignKey(User, verbose_name='Usuário', on_delete=models.CASCADE, related_name='profiles')
    name = models.CharField(verbose_name='Nome', max_length=255, help_text='Nome e sobrenome')
    phone = models.CharField(verbose_name='Telefone', max_length=11)
    cpf = models.CharField(verbose_name='CPF', max_length=11, null=True, blank=True)
    pay_method = models.CharField(verbose_name='Forma de Pagamento', max_length=255, choices=PAY_METHOD,
                                  default=BILLET)
    email = models.EmailField(verbose_name='Email', null=True, blank=True)
    observation = models.TextField(verbose_name='Observação', null=True, blank=True)

    @property
    def get_phone_formated(self):
        return Phone(self.phone).format()

    @property
    def get_total_amount(self):
        values = ProfileUser.objects.filter(
            profile=self).values('profile').order_by('profile').annotate(total=Sum('value'))
        if values:
            return values[0].get('total')
        return None


class ProfileUser(AbstractBaseModel):

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'
        ordering = ['expiration', '-created_at']
        permissions = [
            ('list_profileuser', 'Pode Listar Usuários do Perfil'),
        ]

    objects = ProfileUserManager()

    ACTIVE = 'active'
    EXPIRED = 'expired'
    IN_TEST = 'in_test'
    WAITING = 'waiting_payment'

    STATUS = [
        (ACTIVE, 'Ativo'),
        (WAITING, 'Aguardando pagamento'),
        (EXPIRED, 'Vencido'),
        (IN_TEST, 'Em teste')
    ]

    profile = models.ForeignKey(Profile, verbose_name='Perfil', on_delete=models.CASCADE, related_name='users')
    panel = models.ForeignKey(Panel, verbose_name='Painel', on_delete=models.CASCADE, related_name='users')
    username = models.CharField(verbose_name='Usuário', max_length=255)
    password = models.CharField(verbose_name='Senha', max_length=255)
    value = models.DecimalField(verbose_name='Valor', max_digits=11, decimal_places=2)
    points = models.PositiveSmallIntegerField(verbose_name='Pontos', default=1)
    expiration = models.DateField(verbose_name='Expiração')
    status = models.CharField(verbose_name='Status', max_length=255, choices=STATUS, default=IN_TEST)
    observation = models.TextField(verbose_name='Observação', null=True, blank=True)


auditlog.register(Profile)
auditlog.register(ProfileUser)

ticket_admin/custom_profile/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.forms import AuthenticationForm

from ticket_admin.core import utils
from ticket_admin.panel.models import Panel
from ticket_admin.custom_profile import models


class LoginForm(AuthenticationForm):

    username = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Usuário'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Senha'}))


class ProfileForm(forms.ModelForm):

    class Meta:
        model = models.Profile
        exclude = ['user', 'deleted_at']

    cpf = forms.CharField(label='CPF', max_length=14, required=False)
    phone = forms.CharField(label='Telefone')

    def clean_cpf(self):
        cpf = self.cleaned_data.get('cpf')
        if cpf:
            cpf = utils.CPF(cpf)
            if not cpf.validate():
                raise forms.ValidationError('CPF inválido!')
            cpf = cpf.cleaning()
        return cpf

    def clean_phone(self):
        return utils.Phone(self.cleaned_data.get('phone')).cleaning()


class ProfileUserForm(forms.ModelForm):

    class Meta:
        model = models.ProfileUser
        exclude = ['status', 'deleted_at']

    expiration = forms.DateField(initial=datetime.now().date(), widget=forms.HiddenInput())
    value = forms.CharField(label='Valor', max_length=10)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields.get('profile').label = 'Cliente'
            self.fields.get('panel').queryset = Panel.objects.filter(user=user)
            self.fields.get('profile').queryset = models.Profile.objects.filter(user=user)

    def clean_value(self):
        value = self.cleaned_data.get('value')
        return value.replace('.', '').replace(',', '.')


ProfileUserFormSet = forms.inlineformset_factory(models.Profile, models.ProfileUser,
                                                 form=ProfileUserForm, extra=3, max_num=3, can_delete=False)

ticket_admin/custom_profile/views/profile.py
from django.db.models import Q
from django.db import transaction
from django.urls import reverse_lazy

from ticket_admin.core import views
from ticket_admin.custom_profile import models, forms


class ProfileListView(views.BaseListView):

    model = models.Profile
    template_name = 'profile/list.html'
    permission_required = ['custom_profile.list_profile']

    def get_queryset(self):
        object_list = super().get_queryset().filter(user=self.request.user)
        text_filter = self.request.GET.get('q')
        if text_filter:
            object_list = object_list.filter(
                Q(name__icontains=text_filter) |
                Q(phone__icontains=text_filter))
        return object_list


class ProfileCreateView(views.BaseCreateView):

    model = models.Profile
    form_class = forms.ProfileForm
    template_name = 'profile/form.html'
    success_url = reverse_lazy('profile:list')
    success_message = 'Usuário cadastrado!'
    permission_required = ['custom_profile.add_profile']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = forms.ProfileUserFormSet(form_kwargs={'user': self.request.user})
        if self.request.POST:
            context['users'] = forms.ProfileUserFormSet(self.request.POST, form_kwargs={'user': self.request.user})
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        context = self.get_context_data()
        users = context.get('users')
        with transaction.atomic():
            self.object = form.save()
            if users.is_valid():
                users.instance = self.object
                users.save()
        return super().form_valid(form)


class ProfileUpdateView(views.BaseUpdateView):

    model = models.Profile
    form_class = forms.ProfileForm
    template_name = 'profile/form.html'
    success_url = reverse_lazy('profile:list')
    success_message = 'Usuário salvo!'
    permission_required = ['custom_profile.change_profile']


class ProfileDeleteView(views.BaseDeleteView):

    model = models.Profile
    template_name = 'profile/list.html'
    success_url = reverse_lazy('profile:list')
    success_message = 'Usuário deletado!'
    permission_required = ['custom_profile.delete_profile']

ticket_admin/custom_profile/views/user.py
from django.db.models import Q
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

from ticket_admin.core import views
from ticket_admin.custom_profile import models, forms


class ProfileUserListView(views.BaseListView):

    model = models.ProfileUser
    template_name = 'profile/users/list.html'
    permission_required = ['custom_profile.list_profileuser']

    def get_profile_uuid(self):
        return self.request.GET.get('profile')

    def get_queryset(self):
        object_list = super().get_queryset().filter(profile__user=self.request.user)
        if self.get_profile_uuid():
            object_list = object_list.filter(profile__uuid=self.get_profile_uuid())

        text_filter = self.request.GET.get('q')
        status_filter = self.request.GET.get('status')
        if text_filter:
            object_list = object_list.filter(
                Q(username__icontains=text_filter) |
                Q(password__icontains=text_filter) |
                Q(profile__name__icontains=text_filter) |
                Q(panel__name__icontains=text_filter) |
                Q(observation__icontains=text_filter) |
                Q(status__icontains=text_filter))
        if status_filter:
            object_list = object_list.filter(status=status_filter)
        return object_list

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        if self.get_profile_uuid():
            context['profile'] = get_object_or_404(models.Profile, uuid=self.get_profile_uuid())
        return context


class ProfileUserCreateView(views.BaseCreateView):

    model = models.ProfileUser
    form_class = forms.ProfileUserForm
    success_message = 'Usuário cadastrado!'
    template_name = 'profile/users/form.html'
    success_url = reverse_lazy('profile:user-list')
    permission_required = ['custom_profile.add_profileuser']

    def get_profile_uuid(self):
        return self.request.GET.get('profile')

    def get_profile(self):
        return get_object_or_404(models.Profile, uuid=self.get_profile_uuid())

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        if self.get_profile_uuid():
            initial['profile'] = self.get_profile().id
        return initial

    def form_valid(self, form):
        if self.get_profile_uuid():
            form.instance.profile = self.get_profile()
        return super().form_valid(form)

    def get_success_url(self):
        url = super().get_success_url()
        if self.get_profile_uuid():
            url += '?profile={}'.format(self.get_profile_uuid())
        return url


class ProfileUserUpdateView(views.BaseUpdateView):

    model = models.ProfileUser
    form_class = forms.ProfileUserForm
    success_message = 'Usuário salvo!'
    template_name = 'profile/users/form.html'
    success_url = reverse_lazy('profile:user-list')
    permission_required = ['custom_profile.change_profileuser']

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        url = super().get_success_url()
        profile_uuid = self.request.GET.get('profile')
        if profile_uuid:
            url += '?profile={}'.format(profile_uuid)
        return url


class ProfileUserDeleteView(views.BaseDeleteView):

    model = models.ProfileUser
    success_message = 'Usuário deletado!'
    template_name = 'profile/users/list.html'
    success_url = reverse_lazy('profile:user-list')
    permission_required = ['custom_profile.delete_profileuser']

    def get_success_url(self):
        url = super().get_success_url()
        profile_uuid = self.request.GET.get('profile')
        if profile_uuid:
            url += '&profile={}'.format(profile_uuid)
        return url

ticket_admin/custom_profile/templates/profile/form.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <section class="content">
    <form method="POST">
      {% csrf_token %}
      <div class="box box-primary border-0 rounded-0 shadow-1">
        <div class="box-header">
          <i class="fas fa-edit mr-2"></i>
          <h3 class="box-title">Formulário de cliente</h3>
        </div>
        <div class="box-body">
          <div class="row">
            <div class="col-md-6">
              {% include 'core/components/field.html' with field=form.name %}
            </div>
            <div class="col-md-6">
              {% include 'core/components/field.html' with field=form.phone class='mask-phone' %}
            </div>
            <div class="col-md-12">
              {% include 'core/components/field.html' with field=form.pay_method %}
            </div>
            <div class="col-md-6">
              {% include 'core/components/field.html' with field=form.cpf class='mask-cpf' %}
            </div>
            <div class="col-md-6">
              {% include 'core/components/field.html' with field=form.email %}
            </div>
            <div class="col-md-12">
              {% include 'core/components/field.html' with field=form.observation %}
            </div>
          </div>
        </div>
      </div>
      {{ users.management_form }}
      {% if perms.custom_profile.list_profileuser %}
        {% for form in users.forms %}
          <div class="box box-primary border-0 rounded-0 shadow-1 {% if not forloop.first %}collapsed-box{% endif %}">
            <div class="box-header">
              <i class="fas fa-edit mr-2"></i>
              <h3 class="box-title">Formulário de usuário</h3>
              <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa {% if forloop.first %}fa-minus{% else %}fa-plus{% endif %}"></i></button>
              </div>
            </div>
            <div class="box-body" {% if not forloop.first %}style="display: none;"{% endif %}>
              {{ form.id }}
              <div class="row">
                <div class="col-md-8">
                  <div class="row">
                    <div class="col-md-6">
                      {% include 'core/components/field.html' with field=form.username %}
                    </div>
                    <div class="col-md-6">
                      {% include 'core/components/field.html' with field=form.password %}
                    </div>
                    <div class="col-md-6">
                      {% include 'core/components/field.html' with field=form.panel %}
                    </div>
                    <div class="col-md-6">
                      {% include 'core/components/field.html' with field=form.value class='mask-money' %}
                    </div>
                    <div class="col-md-12">
                      {% include 'core/components/field.html' with field=form.points %}
                      {% include 'core/components/field.html' with field=form.observation %}
                    </div>
                  </div>
                </div>
                <div class="col-md-4">
                  {{ form.expiration }}
                  <div class="datetimepicker"></div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      {% endif %}
      <button type="submit" class="btn btn-primary flat-right rounded-circle"><i class="fas fa-save"></i></button>
    </form>
  </section>

{% endblock %}
{% block modal %}
  {% include 'core/components/form-error.html' with form=form %}
{% endblock %}
{% block css %}
  <link href="{% static 'plugins/datetimepicker/css/datetimepicker.min.css' %}" rel="stylesheet">
{% endblock %}
{% block js %}
  <script src="{% static 'plugins/moment/moment-with-locales.min.js' %}"></script>
  <script src="{% static 'plugins/locale/pt-br.js' %}"></script>
  <script src="{% static 'plugins/datetimepicker/js/datetimepicker.js' %}"></script>
  <script type="text/javascript">
    $(function(){
      $('.mask-cpf').mask('999.999.999-99');
      $('.mask-phone').mask('(99) 99999-9999');
      $('.mask-money').mask('#.##0,00', {reverse: true});

      // DATETIMEPICKER
      $('.datetimepicker').datetimepicker({
        inline: true,
        sideBySide: true,
        locale: 'pt-br',
        format: 'DD/MM/YYYY'
      });

      $(".datetimepicker").on("dp.change", function (e) {
        $(e.currentTarget).prev().val(e.date.format('YYYY-MM-DD'))
      });
    })
  </script>
{% endblock %}

ticket_admin/custom_profile/templates/profile/list.html
{% extends "base.html" %}
{% load l10n %}

{% block content %}
  <section class="content">
    <div class="box box-primary border-0 rounded-0 shadow-1">
      <div class="box-header">
        <div class="row align-items-center">
          <div class="col-md-8">
            <i class="fas fa-list mr-2"></i>
            <h3 class="box-title">Clientes</h3>
          </div>
          <div class="col-md-4">
            <form class="pb-0" style="min-height: auto;">
              <div class="input-group mb-2">
                <input type="text" name="q" placeholder="Filtro" value="{{ request.GET.q }}" class="form-control">
                <div class="input-group-append">
                  <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="box-body text-center px-0">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th class="border-0 text-left pl-4">Nome</th>
                <th class="border-0">Telefone</th>
                <th class="border-0">Forma de pagamento</th>
                <th class="border-0">Observação</th>
                <th class="border-0" width="250">Ações</th>
              </tr>
            </thead>
            <tbody>
              {% for object in object_list %}
                <tr>
                  <td class="align-middle text-left pl-4">{{ object.name }}</td>
                  <td class="align-middle">
                    <a href="https://api.whatsapp.com/send?phone=55{{ object.phone }}" target="_blank" class="text-success font-weight-bold">
                      {{ object.get_phone_formated }}
                    </a>
                  </td>
                  <td class="align-middle">{{ object.get_pay_method_display }}</td>
                  <td class="align-middle">{{ object.observation|default:'----' }}</td>
                  <td>
                    {% if perms.billet.list_billet and object.cpf and object.email %}
                      <a href="{% url 'billet:create' %}?profile={{ object.uuid }}{% if object.get_total_amount %}&amount={{ object.get_total_amount|unlocalize }}{% endif %}" class="btn btn-outline-info" title="Gerar Boleto"><i class="fas fa-file"></i></a>
                    {% endif %}
                    {% if perms.custom_profile.list_profileuser %}
                      <a href="{% url 'profile:user-list' %}?profile={{ object.uuid }}" class="btn btn-outline-dark" title="Usuários"><i class="fas fa-users"></i></a>
                    {% endif %}
                    <a href="{% url 'profile:update' object.uuid %}" class="btn btn-outline-success" title="Editar"><i class="fas fa-edit"></i></a>
                    <button type="button" data-toggle="modal" data-target="#confirm-{{ object.uuid }}" class="btn btn-outline-danger" title="Deletar"><i class="fas fa-trash"></i></button>
                  </td>
                </tr>
              {% empty %}
                <tr><td colspan="6" class="text-center">Nenhum registro encontrado!</td></tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {% if is_paginated %}
          <div class="px-4">
            {% include 'core/components/pagination.html' with obj=page_obj paginator=paginator %}
          </div>
        {% endif %}
      </div>
    </div>
  </section>
  <a href="{% url 'profile:create' %}" class="btn btn-primary flat-right rounded-circle"><i class="fas fa-plus"></i></a>
{% endblock %}
{% block modal %}
  {% for object in object_list %}
    {% url 'profile:delete' object.uuid as url_delete %}

    {% include 'core/components/modal_confirm.html' with uuid=object.uuid url=url_delete %}
  {% endfor %}
{% endblock %}